# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 47497b5
_src_path: gh:scipp/copier_template
description: Matplotlib replacement for Jupyter that uses WebGL via Pythreejs
max_python: '3.13'
min_python: '3.11'
namespace_package: ''
nightly_deps: ''
orgname: scipp
prettyname: Matplotgl
projectname: matplotgl
related_projects: ''
year: 2025
